export default {
  SUPABASE_URL: "https://fornkcxtsctsfxyxjmna.supabase.co",
  SUPABASE_API_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcm5rY3h0c2N0c2Z4eXhqbW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzU1NDM5MzIsImV4cCI6MTk5MTExOTkzMn0.3P1kK65NqJiUZOD_oH4mKA2de3CnMyKqAOMD8yt0jrs",
  APPLE_CAMERA_AD_UNIT_ID: process.env.APPLE_CAMERA_AD_UNIT_ID,
  APPLE_AUDIO_AD_UNIT_ID: process.env.APPLE_AUDIO_AD_UNIT_ID,
  APPLE_FLASHCARD_AD_UNIT_ID: process.env.APPLE_FLASHCARD_AD_UNIT_ID,
  ANDROID_CAMERA_AD_UNIT_ID: process.env.ANDROID_CAMERA_AD_UNIT_ID,
  ANDROID_AUDIO_AD_UNIT_ID: process.env.ANDROID_AUDIO_AD_UNIT_ID,
  ANDROID_FLASHCARD_AD_UNIT_ID: process.env.ANDROID_FLASHCARD_AD_UNIT_ID,
};
