export default {
  APPLE_CAMERA_AD_UNIT_ID: process.env.APPLE_CAMERA_AD_UNIT_ID,
  APPLE_AUDIO_AD_UNIT_ID: process.env.APPLE_AUDIO_AD_UNIT_ID,
  APPLE_FLASHCARD_AD_UNIT_ID: process.env.APPLE_FLASHCARD_AD_UNIT_ID,
  ANDROID_CAMERA_AD_UNIT_ID: process.env.ANDROID_CAMERA_AD_UNIT_ID,
  ANDROID_AUDIO_AD_UNIT_ID: process.env.ANDROID_AUDIO_AD_UNIT_ID,
  ANDROID_FLASHCARD_AD_UNIT_ID: process.env.ANDROID_FLASHCARD_AD_UNIT_ID,
};
